name: Commit build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.events.commits.*.message), '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.4.22252.9

    - name: restore
      run: dotnet restore Starnight

    - name: pack packages
      run: "mkdir build && dotnet pack Helium.Serialization -p:SymbolPackageFormat=snupkg --include-symbols --include-source -o build -p:BuildNumber=${{ github.run_number }}"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Starnight
        path: ./build/