name: Commit build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.events.commits.*.message), '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.4.22252.9

    - name: restore
      run: dotnet restore Helium.Serialization

    - name: set up clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: build all
      run: make all
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: helium-serialization
        path: ./build/