name: "Test Pull Request"

on:
  pull_request:

jobs:
  build_pr:
    runs-on: "ubuntu-latest"
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        with:
          dotnet-version: "7.0.100-preview.4.22252.9"

      - name: "Build PR"
        run: "dotnet build"