name: "Publish Helium.Serialization Cumulative Release"

on:
  release:
    types: [ "published" ]

jobs:
  publish_release:

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        with:
          dotnet-version: "7.0.100-preview.4.22252.9"
        
      - name: "Restore"
        run: "dotnet restore"

      - name: "Build Nuget Packages"
        run: "mkdir build && dotnet pack -p:SymbolPackageFormat=snupkg --include-symbols --include-source -c Release -o build"

      - name: Publish main package
        run: "dotnet nuget push ./build/* --api-key ${{ secrets.NUGET_API_KEY }} --source NuGet --no-service-endpoint --skip-duplicate"
      
      - name: "Upload Nuget Packages To Github Release"
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
