name: "Publish Helium.Serialization Cumulative Release"

on:
  release:
    types: [ "published" ]

jobs:
  publish_release:

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        with:
          dotnet-version: "7.0.100-preview.4.22252.9"
        
      - name: set up clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
  
      - name: build all
        run: make all

      - name: Publish main package
        run: "dotnet nuget push ./build/* --api-key ${{ secrets.NUGET_API_KEY }} --source NuGet --no-service-endpoint --skip-duplicate"
      
      - name: "Upload Nuget Packages To Github Release"
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
